FROM mcr.microsoft.com/dotnet/framework/sdk:3.5 AS base
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_RUNNING_IN_CONTAINER=true
EXPOSE 80
EXPOSE 443
SHELL ["powershell", "-NoLogo", "-ExecutionPolicy", "Bypass", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
ARG DOT_NET_SDK_VERSION=3.1
RUN Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile "${env:TEMP}\dotnet-install.ps1" ; \
    & "${env:TEMP}\dotnet-install.ps1 -InstallDir 'c:/.dotnet' -Runtime dotnet -Channel ${env:DOT_NET_SDK_VERSION}" ; \
    & "setx PATH \"${env:PATH};c:/.dotnet/\" -m"
SHELL ["cmd.exe", "/s", "/c"]

FROM base AS build
ARG NEXUS_USERNAME
ARG NEXUS_PASSWORD
ARG HDIV_AGENT_VERSION
WORKDIR /src
COPY . .
RUN dotnet nuget add source https://artifacts.hdivsecurity.com/nexus/service/local/nuget/nuget/ --name nexus --username %NEXUS_USERNAME% --password %NEXUS_PASSWORD% --store-password-in-clear-text && \
    dotnet add package Hdiv.AST.Profiler --version %HDIV_AGENT_VERSION% && \ 
    dotnet restore && \
    dotnet build -c Release -o /app/build && \ 
    dotnet publish -c Release -o /app/publish

FROM base AS runtime
WORKDIR /app
COPY --from=build /app/publish .
COPY --from=build /app/build/hdivsecurity ./hdivsecurity
ENTRYPOINT ["dotnet", "insecure-bank-net.dll"]